"""Accessibility / layout invariants per page: alt text on every image and a
declared text-placement layout so words stay legible over art.

See ``methodology/accessibility.md``. These are warnings (a draft can still build),
but they should all be cleared before a book is reviewed.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .report import Report


def _norm_zone(s: str) -> str:
    """Normalize a text-position label for comparison, so 'lower third',
    'lower-third' and 'lowerthird' all compare equal."""
    return re.sub(r"[^a-z]", "", (s or "").lower())


def _rendered_zone_from_sidecar(sidecar: Path) -> str | None:
    """Extract the calm zone the art was actually rendered with, from the
    page-NN.prompt.txt sidecar written at generation time. Returns None if the
    sidecar is missing or has no 'leave the ... as calm' note."""
    if not sidecar.exists():
        return None
    try:
        text = sidecar.read_text(encoding="utf-8")
    except OSError:
        return None
    m = re.search(r"leave the ([^,;.]+?) as calm", text, re.I)
    return m.group(1).strip() if m else None


def check_accessibility(rep: Report, world: Any, story: Any) -> None:
    s = story.data
    where = f"{world.slug}/{story.slug}"
    positions: dict[str, int] = {}
    images_dir = getattr(story, "images_dir", None)
    for p in s.get("pages", []) or []:
        n = p.get("number")
        img = p.get("image", {}) or {}
        if not img.get("alt"):
            rep.warn(f"{where} p{n}: image has no alt text")
        if p.get("kind") not in ("title",) and not p.get("layout"):
            rep.warn(f"{where} p{n}: no layout (text placement) set")
        lay = p.get("layout") or {}
        pos = lay.get("text_position")
        if pos and p.get("kind") not in ("title",):
            positions[pos] = positions.get(pos, 0) + 1
        # Catch drift between the CURRENT text_position and the calm zone actually
        # baked into the rendered art. The page-NN.prompt.txt sidecar records the
        # exact prompt sent to the image model at generation time; if text_position
        # was changed afterwards (or the art was generated by a stale code path),
        # the reader will place text on a part of the art that wasn't kept clear.
        # Fix: regenerate the page, or set text_position back to match the art.
        if pos and images_dir is not None and p.get("kind") not in ("title",):
            sidecar = images_dir / f"page-{n:02d}.prompt.txt"
            rendered = _rendered_zone_from_sidecar(sidecar)
            if rendered is not None and _norm_zone(rendered) != _norm_zone(pos):
                rep.warn(f"{where} p{n}: text_position '{pos}' but the art was "
                         f"rendered with a '{rendered}' calm zone — regenerate the "
                         f"page or set text_position to '{rendered.replace(' ', '-')}'")
    # Nudge authors to vary text placement for visual rhythm — a book where every
    # page's text sits in the same spot reads as a flat wall. The page-layout skill
    # calls for varying placement; this surfaces it as a review-time warning.
    story_pages = sum(1 for p in s.get("pages", []) or [] if p.get("kind") not in ("title",))
    if story_pages >= 6 and len(positions) == 1:
        only = next(iter(positions))
        rep.warn(f"{where}: every story page uses text_position '{only}' — "
                 f"vary placement (top/center/lower-third/left/right) for rhythm")
